#!/bin/bash

set -e

if ! which grip 2>/dev/null 1>/dev/null; then
    if which pip3 2>/dev/null 1>/dev/null; then
        pip3 install grip
    else
        pip install grip
    fi
fi

GRIP=$(which grip)
GRIP_PORT=5069
GRIP_RUNNING_PID=$(ps x | grep "grip" | grep ${GRIP_PORT} | sed -E "s/\s+/;/g" | cut -d ";" -f 2)
GRIP_COMMAND="$GRIP -b ${1} ${GRIP_PORT}"

if [[ ! -z $GRIP_RUNNING_PID ]]; then
    kill -SIGTERM $GRIP_RUNNING_PID
fi

$GRIP_COMMAND 2>/tmp/grip.log 1>/tmp/grip.log &
